# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 5000
format = '$time$cmd_duration$container$all$line_break$character'

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

[cmd_duration]
min_time = 1000
format = '\(+$duration\) '
show_notifications = false

[container]
format = '[$symbol]($style) '
style = 'bold cyan'
symbol = ''

[gcloud]
disabled = true

[git_branch]
always_show_remote = true
format = '[$symbol$branch(  $remote_name)(/$remote_branch)]($style) '

[git_metrics]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[status]
disabled = false
style = 'fg:white bg:red bold'

[time]
disabled = false
format = '[$time]($style)'
time_format = '%F %T '
